name: Check Submission Filenames and System Info

on:
  push:
  workflow_dispatch:

jobs:
  check-submissions:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Check filenames in Submissions directory
        run: |
          echo "🔍 Checking files in Submissions/..."
          invalid_files=$(find Submissions/ -maxdepth 1 -type f ! -name '*Submission*')

          if [ -n "$invalid_files" ]; then
            echo "❌ Found invalid files:"
            echo "$invalid_files"
            exit 1
          else
            echo "✅ All filenames are valid."
          fi

      - name: Gather system information
        run: |
          echo "🖥️ System Information:"
          echo "---- uname -a ----"
          uname -a

          echo "---- CPU Info ----"
          lscpu

          echo "---- Memory Info ----"
          free -h

          echo "---- Disk Info ----"
          df -h

          echo "---- Environment ----"
          env | sort
